### ISSUE TITLE
BUG: incorect error path in vscode

### ISSUE THREAD

**Issue by YPetremann** [justarandomgeek/vscode-factoriomod-debug#10]
If I do :

    require("__mymod__.overwrite.__othermod__.path.to.my.script")
or

    require("overwrite.__othermod__.path.to.my.script")

I see in the call stack

    MOD/mymod__/overwrite/__othermod_nil/path/to/my/script.lua

where it should be

    MOD/mymod_0.18.0/overwrite/__othermod__/path/to/my/script.lua

This bug occur in the vscode part.

**Comment by justarandomgeek** [comment]
0.18.24 should fix this
