### ISSUE TITLE
Debug console from log() within a mod doesn't append runtime or newline

### ISSUE THREAD

**Issue by BurninSun** [justarandomgeek/vscode-factoriomod-debug#111]
Running fmtk in debug mode.

Take the following code: 
```
log("foo") log("goo") log("loo") log("moo")
```
If this is run via Factorio console with `/c`, the VSCode debug console correctly shows:
```
2755.091 Script log("foo") log("goo") log("loo") log("moo"):1: foo
2755.091 Script log("foo") log("goo") log("loo") log("moo"):1: goo
2755.091 Script log("foo") log("goo") log("loo") log("moo"):1: loo
2755.091 Script log("foo") log("goo") log("loo") log("moo"):1: moo
```

However, if this code is within the mod being debugged, it gets appended all into one line:
```
foogooloomoo
```
These should have a newline appended for each call to `log()`

**Comment by justarandomgeek** [comment]
1.1.40 fixes this
