### ISSUE TITLE
Request: Resolve absolute paths

### ISSUE THREAD

**Issue by Inrixia** [justarandomgeek/vscode-factoriomod-debug#114]
Factorio lua does not support relative paths above the current directory. But you can import using absolute paths via `__modname__/path...`

However in doing this you lose all type notation for whatever you import as the types cannot be resolved.

Is it possible to somehow map `__modname__` imports so the types look in the correct folder relative to the project?

**Comment by justarandomgeek** [comment]
[like this?](https://github.com/justarandomgeek/vscode-factoriomod-debug/blob/current/doc/language-lua.md#require)

**Comment by Inrixia** [comment]
Weird since it was not working for me. I'll update here with details of what I was trying to import and my config when I get time.
