### ISSUE TITLE
Does Factorio 1.1.107 break the debug adapter?

### ISSUE THREAD

**Issue by EphDoering** [justarandomgeek/vscode-factoriomod-debug#120]
I saw in the [1.1.107 change log](https://wiki.factorio.com/Version_history/1.1.0#1.1.107):

> Disabled the majority of the lua "debug" library due to security issues.

After I updated I'm now getting:

> 1.938 Mods to disable:Failed to load mods: __debugadapter__/instrument-settings.lua:15: attempt to call field 'getregistry' (a nil value)
> stack traceback:
> 	__debugadapter__/instrument-settings.lua:15: in main chunk
> Mods to be disabled:
> • debugadapter (1.1.42)

If this is a known issue, is there a plan for going forward?

**Comment by justarandomgeek** [comment]
what does Check Config (from the command palate) say?

**Comment by EphDoering** [comment]
Oh weird it still has 1.1.104 listed...

> 024-04-29 21:00:19.500 [info] FMTK 1.1.42
> 2024-04-29 21:00:19.500 [info] Registering Version Selector...
> 2024-04-29 21:00:19.500 [info] Registering Debug Provider...
> 2024-04-29 21:00:19.500 [info] Registering Language Client...
> 2024-04-29 21:00:19.500 [info] Registering Mod Package Provider...
> 2024-04-29 21:00:19.500 [info] Registering Profile Renderer...
> 2024-04-29 21:00:19.500 [info] Registering Custom Editors...
> 2024-04-29 21:00:19.500 [info] Activate Complete
> 2024-04-29 21:00:19.501 [info] Active Factorio version: FA (1.1.104)
> 2024-05-09 21:48:21.472 [info] Check Config:
> 2024-05-09 21:48:21.473 [info] Active Factorio Version: 1.1.104
> 2024-05-09 21:48:21.522 [info] Library bundle OK in c:\Users\\AppData\Roaming\Code\User\workspaceStorage\a0abab6ef892f43cd580f1486a98ca3d\justarandomgeek.factoriomod-debug, generated from Factorio 1.1.104 with FMTK 1.1.42
> 2024-05-09 21:48:21.522 [info] LuaLS 3.8.3 Activated
> 2024-05-09 21:48:21.523 [info] Lua.workspace.userThirdParty: workspace link OK (c:\Users\\AppData\Roaming\Code\User\workspaceStorage\a0abab6ef892f43cd580f1486a98ca3d\justarandomgeek.factoriomod-debug\sumneko-3rd)
> 2024-05-09 21:48:21.523 [info] Lua.workspace.checkThirdParty = ApplyInMemory
> 2024-05-09 21:48:21.523 [info] Lua.workspace.library: /data link OK (c:\Program Files\Factorio\data)

**Comment by justarandomgeek** [comment]
rerun the version selector, and/or find out why the json docs are still old

**Comment by EphDoering** [comment]
It fixed itself! Thanks!
