### ISSUE TITLE
unsupported JSON version 5

### ISSUE THREAD

**Issue by shadoxxhd** [justarandomgeek/vscode-factoriomod-debug#135]
Since factorio 1.1.108, the docs use JSON version 5.

When trying to select the factorio executable to setup the environment, you always get an error "Unable to read JSON docs: Unsupported JSON Version 5".

**Comment by justarandomgeek** [comment]
you're using an old version.

**Comment by shadoxxhd** [comment]
I was using the latest version available from inside VS code...

![grafik](https://github.com/user-attachments/assets/dedef0d0-93f1-4811-aee6-c93b189a8e67)

On the marketplace.visualstudio.com site, there are 3 more versions that don't show up in VS Code for me...

**Comment by justarandomgeek** [comment]
then you're also using an old version of vscode

**Comment by shadoxxhd** [comment]
apparently this was the issue, thanks

**Comment by abaines** [comment]
I had similar recent issue with version 6. Found this and it worked!

Thanks! 🍰 

**NOTE**: I had to update VSC twice...
