### ISSUE TITLE
BUG: changelog BOM cause "Line not in valid block"

### ISSUE THREAD

**Issue by YPetremann** [justarandomgeek/vscode-factoriomod-debug#14]
As the title says, if the changelog file is in UTF-8 with BOM, then it will cause an "Line not in valid block" error.
Should ignore about BOM or cause an error like "unwanted BOM"
As far as I know factorio don't mind about this BOM so I'm pretty sure it can be ignored

**Comment by justarandomgeek** [comment]
I can't reproduce this, are you sure it's not just that your'e missing the opening line of -----?

**Comment by justarandomgeek** [comment]
And it just started doing it, so now it's fixed for the next version!
