### ISSUE TITLE
0.18.26 is not doing anything, 0.18.25 is working as intended

### ISSUE THREAD

**Issue by JensForstmann** [justarandomgeek/vscode-factoriomod-debug#16]
"Install Another Version" via vscode's context menu and select 0.18.25: Everything is working:

- The section "source control: factorio mod packages" is filled with content (my mod) and for the mod the icons appear.
- Pressing F5 launches factorio with the correct parameters.

With the latest (0.18.26) version:

- The section "source control: factorio mod packages" is empty (showing a loading circle when hovering over it, but stays empty).
- Pressing F5 does nothing (the UI overlay with the 6 buttons appears but disappears seconds after).

Don't know how to track down the issue or help with finding the causs... If you need anything that could help let me know

**Comment by justarandomgeek** [comment]
Do you have factorio's data stage caching enabled? The latest version definitely doesn't work well with that, so try disabling it.

**Comment by JensForstmann** [comment]
Nope, haven't touched this setting. The checkbox is unchecked (just looked that up).

I'm curious, but shouldn't the first thing be independent of factorio itself? (The interface to increment the version, setting the changelog timestamp, ...)

**Comment by justarandomgeek** [comment]
A bunch of changes around views in 0.18.28, did this get better or any more describable with that?

**Comment by JensForstmann** [comment]
0.18.28 works fine again. Tested with Factorio 0.18.40.

Thanks for this awesome work!
