### ISSUE TITLE
"LuaBooststrap doesn't contain key get_event_id" when debugging

### ISSUE THREAD

**Issue by typecasto** [justarandomgeek/vscode-factoriomod-debug#160]
I get the following error whenever I try to launch with debugging enabled, even if I don't add any mods:
```
LuaBootstrap doesn't contain key get_event_id.
stack traceback:
	[C]: in function '__index'
	__debugadapter__/stepping.lua:672: in function 'save_event_handler'
	__debugadapter__/stepping.lua:826: in function 'on_event'
	__debugadapter__/debug-control.lua:3: in main chunk
	[C]: in function 'require'
	__debugadapter__/control.lua:13: in main chunk
```

It shows up in a "Notice" textbox whenever I try to enter a world, and it shows in the main menu instead of simulations. 

My workspace is currently set to be the mods folder, but previously I had it set to my specific mod's folder and the same issue occurred.
My Factorio version is 2.0.23 (build 80769 expansion, linux64)

**Comment by justarandomgeek** [comment]
update

**Comment by typecasto** [comment]
Still having this issue after updating, I've got version 2.0.5 of the extension now.
