### ISSUE TITLE
VSCode plugin v2.0.5 crashes with Factorio Stable (2.0.23): LuaBootsrap.get_event_id doesn't exist in the latest stable yet.

### ISSUE THREAD

**Issue by roy-t** [justarandomgeek/vscode-factoriomod-debug#161]
Took me a bit too figure this out. But the VS Code plugin v2.0.5 uses `LuaBootstrap.get_event_id(event)` that is [new](https://lua-api.factorio.com/2.0.27/classes/LuaBootstrap.html) in Factorio experimental 2.0.27 and doesn't exist in the [current stable](https://lua-api.factorio.com/2.0.23/classes/LuaBootstrap.html) 2.0.23.

This leads to the following error when loading the game or loading a level:

> LuaBootstrap doesn't contain key get_event_id.

Hope this helps someone who is Googling for this error.

In VS Code I chose to go back to v2.0.3 of the plugin and everything worked as expected again.

**Comment by justarandomgeek** [comment]
update your factorio
