### ISSUE TITLE
Extra info: I can't generate new versions of the mod correctly

### ISSUE THREAD

**Issue by McGuten** [justarandomgeek/vscode-factoriomod-debug#19]
Hello,

I've been trying to get the addon set up right for a while, but I think there's something I'm doing wrong. 
When I increase the version of a mod it only makes the change inside the info.json, but it doesn't modify the folder name, this is correct? 
When I generate a package from a mod it is generated inside the folder of that mod, shouldn't it be generated in the Mods folder directly? Is there a way to set this up? 

Thanks you for your time and for this great vscode addon!

**Comment by justarandomgeek** [comment]
Renaming folders turns out to be stunningly hard to actually make work correctly, so i just never did it. Factorio supports unzipped folders with no version on them now, so it's not really needed anymore. The zips inside to reduce clutter, I usually end up deleting them almost immediately anyway.

**Comment by McGuten** [comment]
Oh, tons of thanks! I don't know that I will test it tomorrow.

**Comment by McGuten** [comment]
it works so fine, tons of thanks!

**Comment by deitux123** [comment]
@justarandomgeek you mind clarifying how to put zips outside of working directory?
