### ISSUE TITLE
Cannot get this to work.

### ISSUE THREAD

**Issue by Raptor2277** [justarandomgeek/vscode-factoriomod-debug#21]
![image](https://user-images.githubusercontent.com/10181133/91673148-b48eb480-eb00-11ea-9b8f-a3161b632d4c.png)

The output is this.

![image](https://user-images.githubusercontent.com/10181133/91673155-bd7f8600-eb00-11ea-8aa2-7f2afbb45fa4.png)

And in-game its stuck at 3%

![image](https://user-images.githubusercontent.com/10181133/91673164-cbcda200-eb00-11ea-9272-cd6bc2c3e657.png)

**Comment by Raptor2277** [comment]
more autput
![image](https://user-images.githubusercontent.com/10181133/91673361-d0468a80-eb01-11ea-8165-c3792b08e4fa.png)

**Comment by Mernom** [comment]
I managed to boot it once, then the next day I started having the same issue.

**Comment by justarandomgeek** [comment]
unfortunately, there's not really any indication of what's gone wrong here, apart from where it hangs indicating the vscode is not getting correctly connected to stdio. I notice you're both using steam versions, perhaps try a standalone zip install?

**Comment by Mernom** [comment]
The first time I got it to work the day prior, it was the exact same configuration.
Should I try to boot vs in admin mode?

**Comment by justarandomgeek** [comment]
probably fixed by the same fix as #35
