### ISSUE TITLE
Suggestion: Script to run after mod portal upload or push to git in "Publish"

### ISSUE THREAD

**Issue by Bilka2** [justarandomgeek/vscode-factoriomod-debug#24]
Something like ` info.json#/package/scripts/postpublish` after "upload to mod portal" or after "push to git upstream" would be highly appreciated to be able to run scripts after the commits have been pushed to git upstream. I'd need the mod zip to not be deleted yet at that point, if possible.
Thank you!

**Comment by justarandomgeek** [comment]
0.18.42 has this

**Comment by Bilka2** [comment]
Thank you, works like a charm!
