### ISSUE TITLE
un-applied code changes break breakpoint release (Continue)

### ISSUE THREAD

**Issue by muppet9010** [justarandomgeek/vscode-factoriomod-debug#25]
When in a breakpoint and you change the code in VS code and hit Continue the breakpoint finishes, but Factorio stays frozen?
I'm sure I used to write code while in a breakpoint before as it was good to inspect stuff in the current scope.
I know that the debugger lines wouldn't match up with what I had code wise if I'd changed it, but that's fine.

So in the past I could do this:
- Hit break point
- Look at state
- Make code changes
- Hit continue
- the game continued

Now when I do this the game doesn't continue, it just stays frozen, bug the debugger says its not stopped.

After continuing the game I would then save my code, apply it to the mods folder and reload the save to have it applied.
It used to be if I stepped through with code changes the debugger would be out of sync with the code I now had on screen (same AS full VS in c++/c#)
I think it started 2 VS Code updates ago.

**Comment by muppet9010** [comment]
It does seem hit and miss if it goes wrong. However, sometimes just stepping (F10) too fast can also just "get lost".

**Comment by justarandomgeek** [comment]
to some degree i think this is just an unavoidable property of the way i'm horribly abusing the debug prompt to communicate with the game - I can only issue commands to it when it's in the right state, and the only way to know the current state is to have kept track of past actions nearly perfectly. I actually drop some stepping commands if you issue them too fast for that reason too - if you're still running the last step you did, i'm not going to (or *can't*) issue another one yet, so i just discard it. I do occasionally see it just lose sync, but I haven't found any clear repeatable way to do it since i started dropping "too fast" steps.

**Comment by muppet9010** [comment]
I guess there's no way to send a next step regardless of believed state?
As if it gets lost I find changing my current call stack position and back fixes it state. Go to caller function and back to current function. But obviously after clicking Continue the call stack is gone so I can't do this trick.

**Comment by justarandomgeek** [comment]
you seem to be describing two different problems now:

1. The "loss of sync" where the debug communication pipe is just broken, at which point the whole session is just hosed
2. The "mismatched source code" where changes in code cause stack location highlights to be placed incorrectly

**Comment by muppet9010** [comment]
Issue 1 in your list is what I have in both scenarios: change of code can trigger it semi-regularly when I then click Continue, or just it occasionally happens when stepping through. with no code changes.
Issue 2 on your list I just expected and Visual Studio for c# has this. I didn't consider this an issue, just a fact.

**Comment by justarandomgeek** [comment]
changing source cannot cause loss of sync, only mismatch on break, it doesn't emit any debug events that could. They're two different issues.

**Comment by justarandomgeek** [comment]
I haven't heard any reports of loss of sync in a while, reopen if this is still happening!
