### ISSUE TITLE
Support command line arguments

### ISSUE THREAD

**Issue by muppet9010** [justarandomgeek/vscode-factoriomod-debug#3]
I would like to be able to add command line arguments to the debugger opening of Factorio. I tried adding these to the `factorioPath` debugger configuration variable, however, that just causes an error on running.

My old Factorio shortcut:
` C:\FactorioModding\bin\x64\factorio.exe --window-size=1280x720`

My attempted factorioPath variable line:
`"factorioPath": "C:/FactorioModding/bin/x64/factorio.exe --window-size=1280x720"`

I have confirmed that without the window-size argument the debugger can launch Factorio and operate successfully.

**Comment by Larandar** [comment]
Looking at the code this is supported (see https://github.com/justarandomgeek/vscode-factoriomod-debug/blob/master/src/factorioModRuntime.ts#L42)

I think this issue should be more about the documentation of available options (I was looking for the `modsPath` option myself)

**Comment by justarandomgeek** [comment]
So does *nobody* look at the intellisense for the json config files, as is standard practice for all of vscode's config files? I suppose i can duplicate all those docs somewhere else too...

**Comment by muppet9010** [comment]
Thanks @Larandar :)

I looked in the settings and the launch.json (Open Configurations). As I know nothing about VSCode other than how to use it as an end user. Being an end user doesn't normally requiring looking at source code, especially when there is a readme that doesn't direct me there.

**Comment by justarandomgeek** [comment]
Right, but when you're in the launch.json and you go to add a new field, it offers you all the valid ones and info about them. ![image](https://user-images.githubusercontent.com/5246445/76590897-085f0000-64c5-11ea-941b-807e734a6293.png)

**Comment by muppet9010** [comment]
Honestly I'm used to configs that have all the settings already in them, if commented out or set to default values. Now you point it out yes its obvious.
