### ISSUE TITLE
Feature request: Option to disable automatic version tag

### ISSUE THREAD

**Issue by Purpzie** [justarandomgeek/vscode-factoriomod-debug#32]
Title explains all. While it seems strange, I have a single repo with multiple small mods, and the tags would all conflict with each other.

**Comment by Purpzie** [comment]
I'm dumb, I just realized I could add the mod name in the tag. I'll close this now.

**Comment by Purpzie** [comment]
Initially closed this thinking I could just make the tag name include the mod name, but tagging a commit also includes the other mods at the time it was tagged, so still not great to use tags anyways

**Comment by justarandomgeek** [comment]
The latest version has this option in info.json
