### ISSUE TITLE
Feature request: Make the default for git_publish_branch also accept "main"

### ISSUE THREAD

**Issue by Purpzie** [justarandomgeek/vscode-factoriomod-debug#33]
Since GitHub has made "main" the default branch name for new repos, it would make sense to accept it as a default branch to publish from. Obviously that would break things for current users though, so perhaps `git_publish_branch` could also accept an array of strings, with `["main", "master"]` being the default value.

**Comment by justarandomgeek** [comment]
The latest version has a setting to configure at the user/workspace level what default it uses when not set in info.json. I am reluctant to expand it to allowing multiple simultaneously as that would allow publishing from the wrong branch sometimes (though, you can turn it off entirely), or to change the default and break existing repos - but perhaps as main continues to take over I will revisit this default again in the future.
