### ISSUE TITLE
Result of using serpent.line in __DebugAdapter.print is "<error>"

### ISSUE THREAD

**Issue by Bilka2** [justarandomgeek/vscode-factoriomod-debug#34]
Hey, I am trying to print a simple table (e.g. `{x = 235, y = 430}`) concatenated into the printed string with serpent.line with __DebugAdapter.print. This results in: `__DebugAdapter.print("Spawned ruin: Size " .. ruin.size .. " Center " .. serpent.line(ruin.center))` -> `Spawned ruin: Size small Center <error>`

Separating the serpent.line from the rest of the string results in this: `__DebugAdapter.print(serpent.line(ruin.center))` -> `<error>`
 
Printing without serpent.line results in this: `__DebugAdapter.print(ruin.center)` -> `{ {<...>}, }`, I have "Factorio > Debug > Expandable Print" turned off.

Printing with the built-in "print" with serpent.line results in this: `print(serpent.line(ruin.center))` -> `{x = -215, y = 55}`

Based on this experimentation, it looks like __DebugAdapter.print is the problem here. I am using version 1.1.4.

**Comment by justarandomgeek** [comment]
That's because it sees the {} serpent makes as the marks to do string interpolation on it. Just do 
```lua
 __DebugAdapter.print("Spawned ruin: Size {ruin.size} Center {ruin.center}")
```
and it'll `describe` things, or if you really must, 
```lua
 __DebugAdapter.print("Spawned ruin: Size {ruin.size} Center {serpent.line(ruin.center)}")
```

**Comment by Bilka2** [comment]
That works perfectly, thank you! From my side this issue could be closed, though things may be more clear in the future if you could mention the print in the String Interpolation section of the readme.

**Comment by justarandomgeek** [comment]
Yeah, i'll add a mention, but It does have its own section immediately after that, which mentions that it does this!
