### ISSUE TITLE
Frozen on "loading mods" when using 0.18.00 as mod version number

### ISSUE THREAD

**Issue by Bilka2** [justarandomgeek/vscode-factoriomod-debug#35]
The behaviour is pretty similar to #21, F5 to launch game which then gets stuck on "Loading mods". I'm adding the output for completeness:
```
using auto-detected config.ini: C:\Users\Erik\Documents\GitHub\Factorio\config\config.ini
using modsPath C:/Users/Erik/Documents/Factorio/mod-dev (launch)
package install debugadapter {"using":"1.1.4","from":"existing","previous":false}
debugadapter enabled in mod-list.json
using dataPath C:/Users/Erik/Documents/GitHub/Factorio/data
loaded ChangeMapSettings 4.1.0 from workspace file:///c%3A/Users/Erik/Documents/Factorio/mod-dev/ChangeMapSettings
loaded base from data file:///c%3A/Users/Erik/Documents/GitHub/Factorio/data/base
loaded debugadapter 1.1.4 from mod zip file:///c%3A/Users/Erik/Documents/Factorio/mod-dev/debugadapter_1.1.4.zip
```

For me, the cause seems to be a mod with `"version": "0.18.00",` in the info.json. Changing the version to 0.18.0 allows the game load as expected. Note that launching the game without the debugger works as expected even with mod version 0.18.00.

**Comment by justarandomgeek** [comment]
It appears the version parsing library that i began using a while ago specifically to deal with leading zeros for me has decided that leading zeros are not valid input and now throws instead. I guess i'll write my own...

**Comment by justarandomgeek** [comment]
this should be fixed in the latest version
