### ISSUE TITLE
Why is the debugadapter mod being disabled when I start debugging?

### ISSUE THREAD

**Issue by Valenor** [justarandomgeek/vscode-factoriomod-debug#36]
I'm attempting to use the plug-in on MacOS against the Steam version of factorio 1.1.21, so I'm unclear if this is a Mac issue, a Steam issue, or a me issue.  The problem is the debugadapter mod keeps being disabled when I go to launch factorio with the F5 Start Debugging option inside VSCode.  This makes the game quickly fail during loading with the error:

`   2.733 Error Util.cpp:83: "--instrument-mod debugadapter" specified but named mod is not enabled`

I have tried to manually enable the mod in the game before quitting and trying the debugger, but I've observed the debugadapter enabled setting inside mod-list.json keeps getting reset to false.  If I manually edit the json to enable it, by the time Steam gives me the confirmation prompt on if I want to launch factorio with command line arguments, the value has been reset to false - so something is disabling it.

If I manually change the value back to enabled:true before accepting the Steam confirmation dialog, the game loads fine with the mod enabled, so I suspect the extension is trying to enable the mod and failing somehow - instead disabling it.  Whether that's an extension bug on Mac or a misconfiguration on my end, I'm unsure.

Here's my launch config:
```
{
    "type": "factoriomod",
    "request": "launch",
     "name": "Factorio Mod Debug",
     "factorioPath": "/Games/Steam/steamapps/common/Factorio/factorio.app/Contents/MacOS/factorio",
     "modsPath": "/Users/<me>/Library/Application Support/factorio/mods/",
     "configPath": "/Users/<me>/Library/Application Support/factorio/config/config.ini"
},
```

I get the same behavior even if I omit the modsPath and configPath values.

**Comment by justarandomgeek** [comment]
https://marketplace.visualstudio.com/items?itemName=justarandomgeek.factoriomod-debug#steam

you'll probably have to make the appid file yourself

**Comment by Valenor** [comment]
Ah, I see.  I had that appid in the folder with the factorio.app package, but really it needs to be in the same folder as the embedded binary (factorio.app/Contents/MacOS/).  Moved it there and now the debugger works.

Thanks!
