### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Whoerr** [justarandomgeek/vscode-factoriomod-debug#37]
- Issue Type: `Performance`
- Extension Name: `factoriomod-debug`
- Extension Version: `1.1.7`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Julie\AppData\Local\Temp\justarandomgeek.factoriomod-debug-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by justarandomgeek** [comment]
You seem to have missed the file that this template tells you to attach, so there's not much i can do with no information
