### ISSUE TITLE
workspace.md

### ISSUE THREAD

**Issue by kryojenik** [justarandomgeek/vscode-factoriomod-debug#39]
The Lua.workspace.library type is expecting an array, not an object.

  "Lua.workspace.library": {

    /* Adjust these to match your Factorio install path */
    "C:/path/to/factorio/data/": true, /* for __base__ and __core__ */
    "C:/path/to/factorio/data/core/lualib": true, /* some basic libs can be required directly*/

  },

Should be:

  "Lua.workspace.library": [

    /* Adjust these to match your Factorio install path */
    "C:/path/to/factorio/data/", /* for __base__ and __core__ */
    "C:/path/to/factorio/data/core/lualib", /* some basic libs can be required directly*/

  ],

**Comment by justarandomgeek** [comment]
fixed
