### ISSUE TITLE
How to edit the default factorioPath?

### ISSUE THREAD

**Issue by moon6969** [justarandomgeek/vscode-factoriomod-debug#4]
I've been debugging loads of different mods lately - love your work thank you!

I can't figure out the VS Code way of updating the default factorioPath - I've managed to edit the package.json for now, but I suspect it may be overwritten on your next update?

Disclaimer: VS Code just doesn't agree with me, so I know little about it.

**Comment by justarandomgeek** [comment]
Why would you need to edit the default? Just edit your launch.json.

**Comment by moon6969** [comment]
Perhaps I'm doing something wrong, but whenever I debug a mod for the first time I either have to copy in the .vscode folder (with my pre-configured launch.json) or update the factorioPath.
I just want to "Add configuration" and go!

**Comment by justarandomgeek** [comment]
So you want the global default for the world to be your specific config?

**Comment by moon6969** [comment]
Errr no... 

If I open the vscode settings tool and search "Factorio" there appear to be a number of other Factorio related defaults ('Factorio > Package: Auto Commit Author' etc.), 

However I know the vscode settings manager does not cover all options, so I hoped there was some obscure command pallety thing that would let me tailor the default in a user config file or similar.

It's Ok, I've a macro to edit the package.json if it changes on upgrade.

Thanks.

**Comment by justarandomgeek** [comment]
You should not be editing package.json. You should be configuring your luanch.json before using the debugger, like how every other debugger works.

**Comment by moon6969** [comment]
>, like how every other debugger works.

Perhaps it's the norm in vscode land, but it's certainly not my experience of debuggers in the last few decades - you configure the debugger once, pointing it to required symbols, runtimes etc.

I had another quick look package.json - it looks to like vs code extensions natively support user configuration of defaults, so not sure why my initial question annoyed you so much?
```
  "contributes": {
    "configuration": [
      {
        "title": "Factorio",
        "properties": {
		"factorio.package.defaultFactorioPath": {
			"type": "string",
			"description": "Default location...",
			"default": "d:/factorio/Factorio_0.18/bin/x64/factorio.exe",
                  }, ...
```

**Comment by Purpzie** [comment]
Apologies if this shouldn't be posted, but I've been needing something like this for a while.

`launch.json` is meant to be committed and used by *multiple people working on the same project.* They'll most likely have different setups, and therefore, different paths.

Having a vscode user setting for this instead makes the most sense and avoids accidental changes in a mod's repo. It also makes it so you don't have to repeat the path every single time.

**Comment by raiguard** [comment]
You can use environment variables for the paths. I forget the exact syntax, but that would fix the issues you bring up.
