### ISSUE TITLE
Undefined fields on game.forces and game.surfaces

### ISSUE THREAD

**Issue by PFQNiet** [justarandomgeek/vscode-factoriomod-debug#41]
I'm assuming it's because they are CustomTables and not tremendously well-defined, but all of `game.forces.player`, `game.forces.neutral`, `game.forces.enemy` and `game.surfaces.nauvis` should be defined. Unfortunately, every reference to them is getting reported as an "undefined field" in my codebase!

**Comment by justarandomgeek** [comment]
Yup, that's exactly why. You can do `["player"]` and similar to make it stop complaining for now if you want. I'll see what i can do about adding proper definitions for the ones that are known to exist, i've got some other types I want to expand the definitions of too.

**Comment by justarandomgeek** [comment]
1.1.14's generator should resolve this
