### ISSUE TITLE
QUESTION: How to specify startup parameter?

### ISSUE THREAD

**Issue by kuxynator** [justarandomgeek/vscode-factoriomod-debug#42]
in launch.json I have specified
'"args": "--mod-directory \"E:\\Program Files\\Factorio\\1.1\\mods-debug\""'
but it seems not to work.

But may be this question is only one of many other. The main question is
"How to setup an development environment." But for this I will create an extra issue.

**Comment by justarandomgeek** [comment]
duplicate #43
