### ISSUE TITLE
Recommends LuaRandomGenerator when math.randomseed() is used in data stage

### ISSUE THREAD

**Issue by Bilka2** [justarandomgeek/vscode-factoriomod-debug#49]
```
18.073 Loading mod steelaxe-subscience 1.1.1 (data.lua)
math.randomseed() has no effect in Factorio. Use LuaRandomGenerator for custom seeded streams
@__steelaxe-subscience__/science.lua:47
```

I really like the warning in general, but for the data and settings stage recommending LuaRandomGenerator isn't ideal since it's not available there.

**Comment by justarandomgeek** [comment]
Is there some data stage alternative i should recommend instead? or just truncate it to the warning itself for data stage?

**Comment by Bilka2** [comment]
I don't know of any data stage alternative, so I was thinking truncate.
