### ISSUE TITLE
Failed to upload zip to Mod Portal: Error: certificate has expired

### ISSUE THREAD

**Issue by hahoyer** [justarandomgeek/vscode-factoriomod-debug#50]
When I upload my mod via website all is ok.
When I try to use the "Upload to Portal" function of factoriomod-debug (1.1.11) it fails with "Failed to upload zip to Mod Portal: Error: certificate has expired"

**Comment by justarandomgeek** [comment]
This is related to the Let's Encrypt cert change recently - there's nothing i can do about it on my end, but there should be a vscode update soon-ish (week or so, if i've understood correctly) that restores functionality. In the mean time, you'll have to upload mods manually!

**Comment by hahoyer** [comment]
ok

**Comment by justarandomgeek** [comment]
For completeness: https://github.com/microsoft/vscode/issues/134244 and https://github.com/electron/electron/pull/31213 and the various things linked from there seem to all be this issue and it's many variants in other extensions.

**Comment by kontu** [comment]
Installed this plugin today on a fully up to date vscode install; still gives the same certificate error
![image](https://user-images.githubusercontent.com/5705697/146977252-e3a26135-aa23-4961-bf33-98a7ec534099.png)

**Comment by TheBrain0110** [comment]
Same here, still getting certificate error on VSCode 1.63.2.

The workaround referenced in https://github.com/microsoft/vscode/issues/136787#issuecomment-968771447 worked for me though.

**Comment by justarandomgeek** [comment]
Yes, the workaround from that issue (`http.systemCertificates: false`) is the best option for now, and vscode's eventual upgrade to electron 16 will be the permanent fix.
