### ISSUE TITLE
Generates some classes wrong from game runtime-api.json it seems

### ISSUE THREAD

**Issue by muppet9010** [justarandomgeek/vscode-factoriomod-debug#58]
Looks like the generated runtime-api.lua from the runtime-api.json is going wrong in a few cases. An example I hit with current versions of Factorio and Debug extension is: 

on_chunk_generated.area is listed as being: `BoundingBox<int,MapPosition<int,double>>`
meaning EmmyLua rejects `on_chunk_generated.area.left_top`

I assume this was mean to cover that a BoundingBox's northwest position can be accessed by either `.left_top` or `[1]`.

Also similar issue with the MapPosition within it not listing `.x` as valid, but expecting `[1]`.

Factorio Game: 1.1.58
Factorio Mod Debug: v1.1.13
I've re-run Generate TypeDefs and reloaded VS Code after this.

**Comment by justarandomgeek** [comment]
1.1.14's generator should resolve this

**Comment by muppet9010** [comment]
seems happy again, nice one :)
