### ISSUE TITLE
Generated API TypeDefs missing ComparatorString details

### ISSUE THREAD

**Issue by muppet9010** [justarandomgeek/vscode-factoriomod-debug#62]
The API game.get_filtered_entity_prototypes filter can take a `comparison` value, but the generated TypeDefs don't provide a definition of its values.

API Call: https://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.get_filtered_entity_prototypes

The filter type of: https://lua-api.factorio.com/latest/Concepts.html#EntityPrototypeFilter
takes a comparison field for some of its types: https://lua-api.factorio.com/latest/Concepts.html#ComparatorString

The generated TypeDef looks to have this as a class, but no fields on it. So the latest Sumneko 3.4.1 won't ever accept a value for it.

Example code where I tried to force the type inline:
`local turrets = game.get_filtered_entity_prototypes({{filter = "turret"}, {mode = "and", filter = "build-base-evolution-requirement", comparison = "≤" --[[@as ComparatorString]], value = evolution}})`
Gives error still:
`Cannot assign `string` to `ComparatorString`.`

**Comment by muppet9010** [comment]
As a temporary work around this made Sumneko happy and is equivalent runtime code for my usage.

```
---@type ComparatorString
local ComparatorString = {
    ["≤"] = "≤"
}

local turrets = game.get_filtered_entity_prototypes({{filter = "turret"}, {mode = "and", filter = "build-base-evolution-requirement", comparison = ComparatorString["≤"], value = evolution}})
```

**Comment by justarandomgeek** [comment]
These should be generated more usefully in 1.1.20
