### ISSUE TITLE
1.1.8 install doesn't provide all globals

### ISSUE THREAD

**Issue by jacobwatkinsgit** [justarandomgeek/vscode-factoriomod-debug#63]
In language.md:
 [https://github.com/justarandomgeek/vscode-factoriomod-debug/commits/92497391a75d798519f08bf2dd724d5bac7cb914/doc/language.md](url) ,
the default settings.json [https://github.com/justarandomgeek/vscode-factoriomod-debug/commit/2180e1566d82a34c70c56a2d45f3d7944ed396d6](url)
and VersionSelector [https://github.com/justarandomgeek/vscode-factoriomod-debug/commit/c784078fa42224217cb618ddbbce46d2acaea71c](url)

There a fewer globals than there used to be, which seem to not be re-implemented anywhere else.

![undefined_global](https://user-images.githubusercontent.com/48106701/177947157-f5576dc4-636f-4dec-9eee-f3b194153c4d.png)

**Comment by jacobwatkinsgit** [comment]
Additional:
Debugger version 1.1.18
Lua 3.4.2
Jansharp's sumneko lua plugin 2022-07-05

**Comment by justarandomgeek** [comment]
Yes, that looks like the correct set of settings now.

**Comment by justarandomgeek** [comment]
1.1.21 will now automatically manage library settings which should fix this
