### ISSUE TITLE
API key cannot be changed

### ISSUE THREAD

**Issue by PrestonLeeC** [justarandomgeek/vscode-factoriomod-debug#65]
Once we've set an API key to use for upload to the mod portal, it cannot ever be changed.

**Comment by justarandomgeek** [comment]
![image](https://user-images.githubusercontent.com/5246445/179417869-db04c735-5014-47b6-a135-dbf2dc1aca67.png)

You can edit or delete it in your OS's control panel for secrets storage

**Comment by justarandomgeek** [comment]
I've added a command in the extension also for the next version
