### ISSUE TITLE
globals still undefined after 1.1.21

### ISSUE THREAD

**Issue by PrestonLeeC** [justarandomgeek/vscode-factoriomod-debug#66]
Hello, sorry to bug you again!
My temporary fix for this issue is to add the globals to the lua diagnostics list...
`
  "Lua.diagnostics.globals": [
    "mods",
    "table_size",
    "log",
    "localised_print",
    "serpent",
    "__DebugAdapter",
    "__Profiler",
    "data", <--
    "script", <--
    "defines", <--
    "game", <--
    "remote", <--
    "global" <--
  ],`

But I'm still getting yellow squigglies below fields like "created_entity" in this example:

`	function(event)
		if event.created_entity.supports_backer_name() then
			event.created_entity.backer_name = ""
		end`

Could you tell me how to manage my library settings manually to fix this? Thank you!

**Comment by justarandomgeek** [comment]
`event` in that example has no type

**Comment by PrestonLeeC** [comment]
Is there a way to specify a type?

**Comment by justarandomgeek** [comment]
If it's really a freestanding function as you've quoted there, you'll just need to [declare them](https://github.com/sumneko/lua-language-server/wiki/Annotations). Otherwise, more context is required.
