### ISSUE TITLE
[Request] Factorio version selector settings overwrite

### ISSUE THREAD

**Issue by muppet9010** [justarandomgeek/vscode-factoriomod-debug#67]
At present when you select a Factorio version within the extension it overwrites the workspace settings for `Lua.workspace.library` to have the 2 Factorio install data folders and the runtime typedef folder it generates and populates.
This means that any manually added extra paths to this setting are lost, i.e. for inclusion of another mod's files type defs or for Nexula's Factorio-API (data stage) type defs.

Is it possible for this to instead add the 3 paths this extension wants to the setting if they aren't present instead, thus leaving any manually added ones untouched.

**Comment by justarandomgeek** [comment]
i already do this

**Comment by muppet9010** [comment]
I am seeing the issue, unless I have somehow messed up something?
![Code_w66nwm5cCj](https://user-images.githubusercontent.com/40836017/181593213-8cdffc15-9282-4974-b0ee-8fca3a955b71.gif)

**Comment by justarandomgeek** [comment]
Bah. one of my .splice()s was missing the ,1 so it cuts off the end. Put your custom entries on the front for now...

**Comment by muppet9010** [comment]
yup adding it as the first one makes it survive, ta :)
