### ISSUE TITLE
Add config option to add globals that aren't warned about by the Debugger in the DEBUG CONSOLE

### ISSUE THREAD

**Issue by muppet9010** [justarandomgeek/vscode-factoriomod-debug#69]
I use a standard global called `MOD` for when I want the odd specific non persisted global objects.
At present the debugger warns about this on startup in the DEBUG CONSOLE:

> Assignment to undefined global: MOD={}

It would be nice if I could add this `MOD` to a setting so that the Debugger didn't warn me about it. I already add it to Sumneko so its typed correctly.

**Comment by justarandomgeek** [comment]
I'm removing this check entirely in the next version.
