### ISSUE TITLE
How do I setup these vs-addon and factorio to work with my mod?

### ISSUE THREAD

**Issue by yuyaryshev** [justarandomgeek/vscode-factoriomod-debug#7]
I can't get to the point when any output or breakpoints are sent to VS Code...
Sadly there is no video tutorial how this can be done for the very first time

- "Adjust the paths and launch settings as required." Can you give an example please?
Is this correct?
        {
            "type": "factoriomod",
            "request": "launch",
            "name": "Factorio Mod Debug",
            "modsPath": "D:/G/Factorio/Factorio_0.18.18/mods",
            "configPath": "D:/G/Factorio/Factorio_0.18.18/config/config.ini",
            "factorioPath": "D:/G/Factorio/Factorio_0.18.18"
        }

- I run factorio with this cmd
D:\G\Factorio\Factorio_0.18.18\bin\x64\factorio.exe --instrument-mod debugadapter
Is that enough?

**Comment by factubsio** [comment]
You run it from inside VScode, just press F5.

`factorioPath `should be the path to the .exe
