### ISSUE TITLE
Option 'instrument-mod' does not exist

### ISSUE THREAD

**Issue by theis999** [justarandomgeek/vscode-factoriomod-debug#70]
When i try to run a pop-up error that says "Option 'instrument-mod' does not exist"
![image](https://user-images.githubusercontent.com/18309265/190383300-b3befeaa-0c0c-4449-9048-a49ce4839e84.png)
With no obvious way to fix the issue. 

I am new to this mod, and it is entirely possible that i have configured it wrong.

**Comment by justarandomgeek** [comment]
What factorio version are you using? Must be pretty old!

**Comment by theis999** [comment]
v1.1.22 - the one available on vscode marketplace

**Comment by raiguard** [comment]
They meant the version of Factorio itself, not the version of the debugger extension. If this error is coming up, then the version of Factorio you are using is very old.

**Comment by theis999** [comment]
I see, yeah i pointed it at the wrong version. It works now thanks
