### ISSUE TITLE
breakpoint when setting a table key's value to nil errors

### ISSUE THREAD

**Issue by muppet9010** [justarandomgeek/vscode-factoriomod-debug#71]
I think this is what was discussed before in Mod-Making discord months back. But I can't see it mentioned as an Issue or in the `todo` file. So logging just in case.

Debugger raises error after breakpoint in table that's had an entries table value nil'd, but code runs fine if no breakpoint. 

```
local things = { stuff = { "a" } }
for key in pairs(things) do
    if key == "stuff" then
        things["stuff"] = nil
        local x = "have this line as a breakpoint"
    end
end
```

Add a breakpoint on the `local x` line. When it's hit just let the code continue running (F5). An error will be raised. If you don't have a breakpoint here then the code runs without error.

**Comment by justarandomgeek** [comment]
1.1.23 finally out
