### ISSUE TITLE
Suggestion: Don't add unneeded "/data/core/lualib" path to Lua.workspace.library setting

### ISSUE THREAD

**Issue by Bilka2** [justarandomgeek/vscode-factoriomod-debug#72]
The extension already adds the path to the Factorio data folder and sumneko already resolves `require`s (e.g. `require("util")`) based on it: 
![Screenshot_20221119_153418](https://user-images.githubusercontent.com/27060268/202856054-a476cbc4-fd75-4290-b65d-60c8a3f31d21.png)

The settings.json above is exactly what the extension generates when selecting a new Factorio version, minus the lualib line in the workspace.library setting.

So, the path to the core lualib is not needed in the workspace library setting and I suggest to remove it.

Extension version 1.1.23
Sumneko version 3.6.3
VSCode 1.73.0
Not using JanSharp's plugin.

**Comment by justarandomgeek** [comment]
done in >= 1.1.24, though i don't remove the old link, you'll have to clean that up manually
