### ISSUE TITLE
Missing support for new built in locale parameters

### ISSUE THREAD

**Issue by Bilka2** [justarandomgeek/vscode-factoriomod-debug#74]
I don't quite get what files are and aren't used for locale support/highlighting/LSP in the extension, but the `__FLUID__` built in parameter is definitely missing. I think `__CONTROL_LEFT_CLICK__`, `__CONTROL_RIGHT_CLICK__`, `__CONTROL_KEY_SHIFT__`, `__CONTROL_KEY_CTRL__` , `__ALT_CONTROL_LEFT_CLICK__n__ ` and `__ALT_CONTROL_RIGHT_CLICK__n__` may also be missing, they are also rather new.

All built in locale is (newly) documented at https://wiki.factorio.com/Tutorial:Localisation#List_of_built-in_parameters.

**Comment by justarandomgeek** [comment]
fixed in >= 1.1.24
