### ISSUE TITLE
How do i actually use this plugin?

### ISSUE THREAD

**Issue by JulianWogersien** [justarandomgeek/vscode-factoriomod-debug#76]
apparently theres a cli utility named fmtk that comes with this but fmtk is not a valid command and when trying to install fmtk with npm, it reports that it couldnt find the package. There is also only two commands in the command palette one of which clears the api key (why is there none to set it?) and to open the factorio mod packages view which also doesnt show anything or give any other functionality.

please document how to use this plugin!

OS: Manjaro linux
Display Server: X11
Kernel: 5.15.79-1-rt54 64bit
vscode version: 1.70.0-insider

**Comment by raiguard** [comment]
With npm, you have to install it globally:
`sudo npm install -g factoriomod-debug`
You only need to install it on npm if you're not using vscode, or if you want to use it on the CLI.

**Comment by JulianWogersien** [comment]
i am using vscode, how do i use the vscode plugin?

**Comment by adamk33n3r** [comment]
I can't figure it out either. It seems to have some things, like `info.json` autocomplete. But it doesn't even know what the global `data` is...


EDIT: I found out from another issue which pointed to this documentation https://github.com/justarandomgeek/vscode-factoriomod-debug/blob/current/doc/workspace.md that you gotta click on the "Factorio unselected" in the bottom status bar and click on your version. That step should really be on the main readme page.

**Comment by GongT** [comment]
My status bar do not have a button "Factorio unselected" 

Compile plugin from source resolve this problem, Can't understand why.

**Comment by justarandomgeek** [comment]
nobody in this thread has provided enough information about their problems for them to be even remotely addressable. Please make your own threads instead of dogpiling on an old unrelated one.
