### ISSUE TITLE
Can't launch debugger after running game via admin

### ISSUE THREAD

**Issue by BurninSun** [justarandomgeek/vscode-factoriomod-debug#78]
Windows install.
I normally run the steam version of Factorio but I have a 2nd standalone copy for testing as well. The mods folder is symlinked between the 2 installs.
When I run the standalone copy, I do so from the command line which requires admin access since its installed in /Program files/. After running that version, attempting to run debug from vscode results in just non stop loading. The following is in the debug console:
```
using modsPath C:/Users/User/AppData/Roaming/Factorio/mods (config)
package install debugadapter {"using":"1.1.28","from":"existing","previous":false}
```
at this point, it just sits there doing nothing. I can stop the debugger which results in this in the console:
```
failed to disable debugadapter in mod-list.json:
Error: EPERM: operation not permitted, open 'C:\Users\User\AppData\Roaming\Factorio\mods\mod-list.json'
```
Running Factorio manually via steam then exiting fixes the problem.

The security permissions get changed on mod-list.json between the two which is causing the problem. No idea how fixable it is.

**Comment by justarandomgeek** [comment]
> which requires admin access since its installed in /Program files/

huh? it shouldn't? it's only reading from in there. The only thing i ever attempt to write in the factorio program dir is the steam appid.txt if applicable, which it wouldn't be in this case.

In any case I'm not explicitly setting permissions anywhere so i would have expected it to inherit them from the `mods` directory, or keep whatever perms it already had...

**Comment by justarandomgeek** [comment]
Is it possible that some other application on your PC has noticed the change to the files and opened them for backup or such, and happens to still be holding them at the time future accesses come in? That often presents as if it is a permission error also. Carbonite had a bad habit of doing things like this to me before I got fed up and binned it!

**Comment by BurninSun** [comment]
>which requires admin access since its installed in /Program files/

That is regarding running Factorio manually via factorio.exe via command line, not through VSCode or with the debugger. Command line requires admin access for writing Factorio's .lock file to /Program files/. But running Factorio via admin in this way results in the mod-list.json file's security properties look like so:
![image](https://user-images.githubusercontent.com/12116957/212615161-0433a63b-11a5-445f-a37d-f630a2fa3479.png)
After that, running Factorio via VSCode with the debugger fails, presumably because of the changed security permissions. Running Factorio via steam reverts the security permissions back to: 
![image](https://user-images.githubusercontent.com/12116957/212615496-c7f4a76b-a249-4c47-b5e3-aee1eb2ebc19.png)
Mostly I was just wondering if you could change the security profile you use for accessing the file, though I'm not sure that's feasible.

**Comment by justarandomgeek** [comment]
I don't use any "security profile", it's [just plain node fs access](https://github.com/justarandomgeek/vscode-factoriomod-debug/blob/b16ce66/src/ModManager.ts#L107)! I'm not really sure there's anything i *can* do about this... 🤔

**Comment by BurninSun** [comment]
Can you at least timeout / error out when unable to read/write to mod-list.json? Currently it sits there seemingly loading forever and only prints an error when pressing stop.

**Comment by justarandomgeek** [comment]
1.1.29 should now fail the launch request if it fails any of the startup steps.
