### ISSUE TITLE
hookData hangs on zipped mod

### ISSUE THREAD

**Issue by Wiwiweb** [justarandomgeek/vscode-factoriomod-debug#87]
My launch config:

```json
    {
      "type": "factoriomod",
      "request": "launch",
      "name": "Factorio Mod Debug (Data)",
      "hookData": true,
      "hookControl": false
    },
```

Launch hangs on this log line:
> 45.464 Loading mod shield-projector 0.1.6 (data.lua)

Then I unzip the `shield-projector` mod and run again. The launch now goes further but then hangs on another zipped mod (`stargate`):

>   41.939 Loading mod shield-projector 0.1.6 (data.lua)
  42.273 Loading mod space-exploration-menu-simulations 0.6.8 (data.lua)
  42.410 Loading mod stargate 0.1.4 (data.lua)

In these examples I'm launching from the repository of an unrelated mod (`aai-signal-transmission`).

Factorio log + FMTK log for the second launch:
[factorio+fmtk.log](https://github.com/justarandomgeek/vscode-factoriomod-debug/files/11471157/factorio%2Bfmtk.log)

**Comment by justarandomgeek** [comment]
1.1.32 should fix this
