### ISSUE TITLE
Stuck on "Loading sounds" while debugging.

### ISSUE THREAD

**Issue by gabfv** [justarandomgeek/vscode-factoriomod-debug#94]
Hi,
I'm using this wonderful extension for vscode but when I try to debug any mods, the game hangs up at "Loading sounds..." at 95%. It doesn't seem to matter what type of debug launch I'm doing (I'm using the default launch.json as below). I've tried clearing out my .vscode folder and regenerate them when the extension asks me to but no success either. The versions are below:
justarandomgeek.factoriomod-debug: 1.1.34
Factorio (Steam): 1.1.87

launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "factoriomod",
            "request": "launch",
            "name": "Factorio Mod Debug"
        },
        {
            "type": "factoriomod",
            "request": "launch",
            "name": "Factorio Mod Debug (Settings & Data)",
            "hookSettings": true,
            "hookData": true
        },
        {
            "type": "factoriomod",
            "request": "launch",
            "name": "Factorio Mod Debug (Profile)",
            "hookMode": "profile"
        }
    ]
}
```

Snippet of settings.json:
```json
    "factorio.versions": [
        {
            "name": "steam-main",
            "factorioPath": "c:\\Apps\\Steam\\steamapps\\common\\Factorio\\bin\\x64\\factorio.exe",
            "active": true
        }
    ]
```

The last few lines in vscode's "debug console" I see:
```log
  27.309 Custom mipmaps uploaded (3494)
  27.318 Custom inputs active: 168
debugadapter registered for level in Instrument Mode
```

**Comment by gabfv** [comment]
Deactivating every mods make me able to launch the debugger... I've got a fairly long list of mods but I'll try to investigate which mod is causing the issue.

**Comment by justarandomgeek** [comment]
This is probably related to a change in how bytecode is dumped in .33, since you're not on factorio .89 yet, you can just roll back to .32 for a little while. I'll have an update out soon that should address this...

**Comment by gabfv** [comment]
Ah, alright. I was hoping to create a mod base off Space Exploration but looks like even the bare minimal amount of mods (SE with its dependency, Blueprint Sandbox and my currently unlisted mod) doesn't load. I guess I'll wait for the .89 update!

**Comment by justarandomgeek** [comment]
yeah, the other report i had about this was for SE also - but you said you're on factorio 87, so you should still be able to use older debugger versions as well! (factorio >=89 has the new docs, and thus requires new debugger to read them)

**Comment by gabfv** [comment]
Oh I've forgotten you can use other versions in vscode extensions. Thanks!
Edit: for anyone else trying to debug mods, I used the extension 1.1.32

**Comment by justarandomgeek** [comment]
1.1.35 should resolve this
