### ISSUE TITLE
Unsupported JSON Version 4

### ISSUE THREAD

**Issue by Levi--G** [justarandomgeek/vscode-factoriomod-debug#96]
Hi,

Ive just tried the plugin for the first time and after selecting the factorio exe i am greeted with "Unsupported JSON Version 4" Is there any way to get it working on the current factorio version?

Thanks

**Comment by justarandomgeek** [comment]
You need to update.

**Comment by Levi--G** [comment]
Hi, sorry but update what exactly? My factorio is up to date with steam and I just today installed the last version of the plugin in vs code?

**Comment by Levi--G** [comment]
I see, i was missing a VS code update that i had to click "check for updates" manually for for some reason :) My bad...
