### ISSUE TITLE
Documentation Links for runtime objects breaks with API docs redirect

### ISSUE THREAD

**Issue by muppet9010** [justarandomgeek/vscode-factoriomod-debug#98]
The documentation link included with the typeDefs goes to an old URL it seems. When the Factorio API website redirects it drops off the function part of the URL.

Factorio object:  game.get_filtered_entity_prototypes()
Documentation Link in typedefs: https://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.get_filtered_entity_prototypes
Factorio API Website redirects to: https://lua-api.factorio.com/latest/classes/LuaGameScript.html
note the loss of the function to jump to.

I had to free type the Documentation Link on typedefs so if there's a typo above that's probably on me.

**Comment by justarandomgeek** [comment]
yeah a lot of the links are still broken because teh upgrade to v4 json docs is still only kinda half done

**Comment by justarandomgeek** [comment]
afaik all the links should be fixed in 1.1.38, let me know if you find more broken ones!
